<?php


 function autoload_c47ce1503dfd14290bbf73600e3de4d5($class)
{
    $classes = array(
        'UkMail\Test\Tracking\Service' => __DIR__ .'/Service.php',
        'UkMail\Test\Tracking\ManifestDomesticV1' => __DIR__ .'/ManifestDomesticV1.php',
        'UkMail\Test\Tracking\DomesticV1' => __DIR__ .'/DomesticV1.php',
        'UkMail\Test\Tracking\ArrayOfDomesticSubV1' => __DIR__ .'/ArrayOfDomesticSubV1.php',
        'UkMail\Test\Tracking\DomesticSubV1' => __DIR__ .'/DomesticSubV1.php',
        'UkMail\Test\Tracking\ArrayOfBoxV1' => __DIR__ .'/ArrayOfBoxV1.php',
        'UkMail\Test\Tracking\BoxV1' => __DIR__ .'/BoxV1.php',
        'UkMail\Test\Tracking\ManifestDomesticV1Response' => __DIR__ .'/ManifestDomesticV1Response.php',
        'UkMail\Test\Tracking\ManifestResult' => __DIR__ .'/ManifestResult.php',
        'UkMail\Test\Tracking\ResultState' => __DIR__ .'/ResultState.php',
        'UkMail\Test\Tracking\ArrayOfError' => __DIR__ .'/ArrayOfError.php',
        'UkMail\Test\Tracking\Error' => __DIR__ .'/Error.php',
        'UkMail\Test\Tracking\ErrorType' => __DIR__ .'/ErrorType.php',
        'UkMail\Test\Tracking\ManifestThirdPartyCollectionV1' => __DIR__ .'/ManifestThirdPartyCollectionV1.php',
        'UkMail\Test\Tracking\ThirdPartyCollectionV1' => __DIR__ .'/ThirdPartyCollectionV1.php',
        'UkMail\Test\Tracking\ManifestThirdPartyCollectionV1Response' => __DIR__ .'/ManifestThirdPartyCollectionV1Response.php',
        'UkMail\Test\Tracking\ManifestCarriageForwardCollectionV1' => __DIR__ .'/ManifestCarriageForwardCollectionV1.php',
        'UkMail\Test\Tracking\CarriageForwardCollectionV1' => __DIR__ .'/CarriageForwardCollectionV1.php',
        'UkMail\Test\Tracking\ManifestCarriageForwardCollectionV1Response' => __DIR__ .'/ManifestCarriageForwardCollectionV1Response.php',
        'UkMail\Test\Tracking\ManifestInternationalV1' => __DIR__ .'/ManifestInternationalV1.php',
        'UkMail\Test\Tracking\InternationalV1' => __DIR__ .'/InternationalV1.php',
        'UkMail\Test\Tracking\ManifestInternationalV1Response' => __DIR__ .'/ManifestInternationalV1Response.php',
        'UkMail\Test\Tracking\ManifestParcelScanV1' => __DIR__ .'/ManifestParcelScanV1.php',
        'UkMail\Test\Tracking\ParcelScanV1' => __DIR__ .'/ParcelScanV1.php',
        'UkMail\Test\Tracking\ManifestParcelScanV1Response' => __DIR__ .'/ManifestParcelScanV1Response.php',
        'UkMail\Test\Tracking\GetConsignmentNumberRangeForAccountV1' => __DIR__ .'/GetConsignmentNumberRangeForAccountV1.php',
        'UkMail\Test\Tracking\GetConsignmentNumberRangeForAccountV1Response' => __DIR__ .'/GetConsignmentNumberRangeForAccountV1Response.php',
        'UkMail\Test\Tracking\ConsignmentNumberRangeResult' => __DIR__ .'/ConsignmentNumberRangeResult.php',
        'UkMail\Test\Tracking\ConsignmentNumberRange' => __DIR__ .'/ConsignmentNumberRange.php',
        'UkMail\Test\Tracking\ActivationStatus' => __DIR__ .'/ActivationStatus.php',
        'UkMail\Test\Tracking\GetSignaturesForConsignmentNumberV1' => __DIR__ .'/GetSignaturesForConsignmentNumberV1.php',
        'UkMail\Test\Tracking\ImageType' => __DIR__ .'/ImageType.php',
        'UkMail\Test\Tracking\GetSignaturesForConsignmentNumberV1Response' => __DIR__ .'/GetSignaturesForConsignmentNumberV1Response.php',
        'UkMail\Test\Tracking\SignatureResult' => __DIR__ .'/SignatureResult.php',
        'UkMail\Test\Tracking\ArrayOfSignatureDetails' => __DIR__ .'/ArrayOfSignatureDetails.php',
        'UkMail\Test\Tracking\SignatureDetails' => __DIR__ .'/SignatureDetails.php',
        'UkMail\Test\Tracking\ConsignmentTrackingTestWebServiceV1' => __DIR__ .'/ConsignmentTrackingTestWebServiceV1.php',
        'UkMail\Test\Tracking\ConsignmentTrackingTestWebServiceV1Response' => __DIR__ .'/ConsignmentTrackingTestWebServiceV1Response.php',
        'UkMail\Test\Tracking\ConsTrackingTestResult' => __DIR__ .'/ConsTrackingTestResult.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetConsignmentDetailsV1' => __DIR__ .'/ConsignmentTrackingGetConsignmentDetailsV1.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetConsignmentDetailsV1Response' => __DIR__ .'/ConsignmentTrackingGetConsignmentDetailsV1Response.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetDetailsResult' => __DIR__ .'/ConsignmentTrackingGetDetailsResult.php',
        'UkMail\Test\Tracking\ArrayOfGetConsignmentDetailsSub' => __DIR__ .'/ArrayOfGetConsignmentDetailsSub.php',
        'UkMail\Test\Tracking\GetConsignmentDetailsSub' => __DIR__ .'/GetConsignmentDetailsSub.php',
        'UkMail\Test\Tracking\ArrayOfGetConsignmentDetailsPod' => __DIR__ .'/ArrayOfGetConsignmentDetailsPod.php',
        'UkMail\Test\Tracking\GetConsignmentDetailsPod' => __DIR__ .'/GetConsignmentDetailsPod.php',
        'UkMail\Test\Tracking\ArrayOfGetConsignmentDetailsStatus' => __DIR__ .'/ArrayOfGetConsignmentDetailsStatus.php',
        'UkMail\Test\Tracking\GetConsignmentDetailsStatus' => __DIR__ .'/GetConsignmentDetailsStatus.php',
        'UkMail\Test\Tracking\ConsignmentTrackingSearchV1' => __DIR__ .'/ConsignmentTrackingSearchV1.php',
        'UkMail\Test\Tracking\ConsignmentTrackingSearchV1Response' => __DIR__ .'/ConsignmentTrackingSearchV1Response.php',
        'UkMail\Test\Tracking\ConsignmentTrackingSearchResult' => __DIR__ .'/ConsignmentTrackingSearchResult.php',
        'UkMail\Test\Tracking\ArrayOfConsignmentSearchResult' => __DIR__ .'/ArrayOfConsignmentSearchResult.php',
        'UkMail\Test\Tracking\ConsignmentSearchResult' => __DIR__ .'/ConsignmentSearchResult.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetStatusV1' => __DIR__ .'/ConsignmentTrackingGetStatusV1.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetStatusV1Response' => __DIR__ .'/ConsignmentTrackingGetStatusV1Response.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetStatusResult' => __DIR__ .'/ConsignmentTrackingGetStatusResult.php',
        'UkMail\Test\Tracking\ArrayOfGetConsignmentStatus' => __DIR__ .'/ArrayOfGetConsignmentStatus.php',
        'UkMail\Test\Tracking\GetConsignmentStatus' => __DIR__ .'/GetConsignmentStatus.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetFullDetailsV1' => __DIR__ .'/ConsignmentTrackingGetFullDetailsV1.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetFullDetailsV1Response' => __DIR__ .'/ConsignmentTrackingGetFullDetailsV1Response.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetFullDetailsResult' => __DIR__ .'/ConsignmentTrackingGetFullDetailsResult.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetFullDetails' => __DIR__ .'/ConsignmentTrackingGetFullDetails.php',
        'UkMail\Test\Tracking\ArrayOfGetFullConsignmentDetailsPod' => __DIR__ .'/ArrayOfGetFullConsignmentDetailsPod.php',
        'UkMail\Test\Tracking\GetFullConsignmentDetailsPod' => __DIR__ .'/GetFullConsignmentDetailsPod.php',
        'UkMail\Test\Tracking\ArrayOfConsignmentScan' => __DIR__ .'/ArrayOfConsignmentScan.php',
        'UkMail\Test\Tracking\ConsignmentScan' => __DIR__ .'/ConsignmentScan.php',
        'UkMail\Test\Tracking\ArrayOfConsignmentDiscrepency' => __DIR__ .'/ArrayOfConsignmentDiscrepency.php',
        'UkMail\Test\Tracking\ConsignmentDiscrepency' => __DIR__ .'/ConsignmentDiscrepency.php',
        'UkMail\Test\Tracking\ArrayOfConsignmentNote' => __DIR__ .'/ArrayOfConsignmentNote.php',
        'UkMail\Test\Tracking\ConsignmentNote' => __DIR__ .'/ConsignmentNote.php',
        'UkMail\Test\Tracking\ArrayOfConsignmentPOC' => __DIR__ .'/ArrayOfConsignmentPOC.php',
        'UkMail\Test\Tracking\ConsignmentPOC' => __DIR__ .'/ConsignmentPOC.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetConsignmentDetailsV2' => __DIR__ .'/ConsignmentTrackingGetConsignmentDetailsV2.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetConsignmentDetailsV2Response' => __DIR__ .'/ConsignmentTrackingGetConsignmentDetailsV2Response.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetDetailsResultV2' => __DIR__ .'/ConsignmentTrackingGetDetailsResultV2.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetConsignmentDetailsV3' => __DIR__ .'/ConsignmentTrackingGetConsignmentDetailsV3.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetConsignmentDetailsV3Response' => __DIR__ .'/ConsignmentTrackingGetConsignmentDetailsV3Response.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetDetailsResultV3' => __DIR__ .'/ConsignmentTrackingGetDetailsResultV3.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetFullDetailsV2' => __DIR__ .'/ConsignmentTrackingGetFullDetailsV2.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetFullDetailsV2Response' => __DIR__ .'/ConsignmentTrackingGetFullDetailsV2Response.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetFullDetailsResultV2' => __DIR__ .'/ConsignmentTrackingGetFullDetailsResultV2.php',
        'UkMail\Test\Tracking\ArrayOfGetFullConsignmentDetailsPodV2' => __DIR__ .'/ArrayOfGetFullConsignmentDetailsPodV2.php',
        'UkMail\Test\Tracking\GetFullConsignmentDetailsPodV2' => __DIR__ .'/GetFullConsignmentDetailsPodV2.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetFullDetailsV3' => __DIR__ .'/ConsignmentTrackingGetFullDetailsV3.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetFullDetailsV3Response' => __DIR__ .'/ConsignmentTrackingGetFullDetailsV3Response.php',
        'UkMail\Test\Tracking\ConsignmentTrackingGetFullDetailsResultV3' => __DIR__ .'/ConsignmentTrackingGetFullDetailsResultV3.php',
        'UkMail\Test\Tracking\GetEstimatedTimeOfArrivalForPostcode' => __DIR__ .'/GetEstimatedTimeOfArrivalForPostcode.php',
        'UkMail\Test\Tracking\GetEstimatedTimeOfArrivalForPostcodeResponse' => __DIR__ .'/GetEstimatedTimeOfArrivalForPostcodeResponse.php',
        'UkMail\Test\Tracking\GetEstimatedTimeOfArrivalForPostcodeResult' => __DIR__ .'/GetEstimatedTimeOfArrivalForPostcodeResult.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_c47ce1503dfd14290bbf73600e3de4d5');

// Do nothing. The rest is just leftovers from the code generation.
{
}
